### YamlMime:ManagedReference
items:
- uid: ModLib.Options.ConfigValue.ValueKind
  commentId: T:ModLib.Options.ConfigValue.ValueKind
  id: ConfigValue.ValueKind
  parent: ModLib.Options
  children:
  - ModLib.Options.ConfigValue.ValueKind.Bool
  - ModLib.Options.ConfigValue.ValueKind.Float
  - ModLib.Options.ConfigValue.ValueKind.Int
  - ModLib.Options.ConfigValue.ValueKind.String
  langs:
  - csharp
  - vb
  name: ConfigValue.ValueKind
  nameWithType: ConfigValue.ValueKind
  fullName: ModLib.Options.ConfigValue.ValueKind
  type: Enum
  source:
    remote:
      path: ModLib/Options/ConfigValue.cs
      branch: devel
      repo: https://github.com/AydenTFoxx/ModLib.git
    id: ValueKind
    path: ../ModLib/Options/ConfigValue.cs
    startLine: 234
  assemblies:
  - ModLib
  namespace: ModLib.Options
  summary: The kind of the internally held value from the configurable struct.
  example: []
  syntax:
    content: 'public enum ConfigValue.ValueKind : byte'
    content.vb: Public Enum ConfigValue.ValueKind As Byte
- uid: ModLib.Options.ConfigValue.ValueKind.Int
  commentId: F:ModLib.Options.ConfigValue.ValueKind.Int
  id: Int
  parent: ModLib.Options.ConfigValue.ValueKind
  langs:
  - csharp
  - vb
  name: Int
  nameWithType: ConfigValue.ValueKind.Int
  fullName: ModLib.Options.ConfigValue.ValueKind.Int
  type: Field
  source:
    remote:
      path: ModLib/Options/ConfigValue.cs
      branch: devel
      repo: https://github.com/AydenTFoxx/ModLib.git
    id: Int
    path: ../ModLib/Options/ConfigValue.cs
    startLine: 239
  assemblies:
  - ModLib
  namespace: ModLib.Options
  summary: The internally held value is of type <xref href="System.Int32" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: Int = 0
    return:
      type: ModLib.Options.ConfigValue.ValueKind
- uid: ModLib.Options.ConfigValue.ValueKind.Float
  commentId: F:ModLib.Options.ConfigValue.ValueKind.Float
  id: Float
  parent: ModLib.Options.ConfigValue.ValueKind
  langs:
  - csharp
  - vb
  name: Float
  nameWithType: ConfigValue.ValueKind.Float
  fullName: ModLib.Options.ConfigValue.ValueKind.Float
  type: Field
  source:
    remote:
      path: ModLib/Options/ConfigValue.cs
      branch: devel
      repo: https://github.com/AydenTFoxx/ModLib.git
    id: Float
    path: ../ModLib/Options/ConfigValue.cs
    startLine: 243
  assemblies:
  - ModLib
  namespace: ModLib.Options
  summary: The internally held value is of type <xref href="System.Single" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: Float = 1
    return:
      type: ModLib.Options.ConfigValue.ValueKind
- uid: ModLib.Options.ConfigValue.ValueKind.Bool
  commentId: F:ModLib.Options.ConfigValue.ValueKind.Bool
  id: Bool
  parent: ModLib.Options.ConfigValue.ValueKind
  langs:
  - csharp
  - vb
  name: Bool
  nameWithType: ConfigValue.ValueKind.Bool
  fullName: ModLib.Options.ConfigValue.ValueKind.Bool
  type: Field
  source:
    remote:
      path: ModLib/Options/ConfigValue.cs
      branch: devel
      repo: https://github.com/AydenTFoxx/ModLib.git
    id: Bool
    path: ../ModLib/Options/ConfigValue.cs
    startLine: 247
  assemblies:
  - ModLib
  namespace: ModLib.Options
  summary: The internally held value is of type <xref href="System.Boolean" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: Bool = 2
    return:
      type: ModLib.Options.ConfigValue.ValueKind
- uid: ModLib.Options.ConfigValue.ValueKind.String
  commentId: F:ModLib.Options.ConfigValue.ValueKind.String
  id: String
  parent: ModLib.Options.ConfigValue.ValueKind
  langs:
  - csharp
  - vb
  name: String
  nameWithType: ConfigValue.ValueKind.String
  fullName: ModLib.Options.ConfigValue.ValueKind.String
  type: Field
  source:
    remote:
      path: ModLib/Options/ConfigValue.cs
      branch: devel
      repo: https://github.com/AydenTFoxx/ModLib.git
    id: String
    path: ../ModLib/Options/ConfigValue.cs
    startLine: 251
  assemblies:
  - ModLib
  namespace: ModLib.Options
  summary: The internally held value is of type <xref href="System.String" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: String = 3
    return:
      type: ModLib.Options.ConfigValue.ValueKind
references:
- uid: ModLib.Options
  commentId: N:ModLib.Options
  href: ModLib.html
  name: ModLib.Options
  nameWithType: ModLib.Options
  fullName: ModLib.Options
  spec.csharp:
  - uid: ModLib
    name: ModLib
    href: ModLib.html
  - name: .
  - uid: ModLib.Options
    name: Options
    href: ModLib.Options.html
  spec.vb:
  - uid: ModLib
    name: ModLib
    href: ModLib.html
  - name: .
  - uid: ModLib.Options
    name: Options
    href: ModLib.Options.html
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: ModLib.Options.ConfigValue.ValueKind
  commentId: T:ModLib.Options.ConfigValue.ValueKind
  parent: ModLib.Options
  href: ModLib.Options.ConfigValue.html
  name: ConfigValue.ValueKind
  nameWithType: ConfigValue.ValueKind
  fullName: ModLib.Options.ConfigValue.ValueKind
  spec.csharp:
  - uid: ModLib.Options.ConfigValue
    name: ConfigValue
    href: ModLib.Options.ConfigValue.html
  - name: .
  - uid: ModLib.Options.ConfigValue.ValueKind
    name: ValueKind
    href: ModLib.Options.ConfigValue.ValueKind.html
  spec.vb:
  - uid: ModLib.Options.ConfigValue
    name: ConfigValue
    href: ModLib.Options.ConfigValue.html
  - name: .
  - uid: ModLib.Options.ConfigValue.ValueKind
    name: ValueKind
    href: ModLib.Options.ConfigValue.ValueKind.html
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.single
  name: float
  nameWithType: float
  fullName: float
  nameWithType.vb: Single
  fullName.vb: Single
  name.vb: Single
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
